const data = [
    {
        id: 1,
        nome: "IAGO LEAL DE FREITAS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 2,
        inscricao: 252400009,
        nome: "NEIDE DA ROCHA DO NASCIMENTO",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 3,
        inscricao: 252400015,
        nome: "LUCIMARLY TAVARES DA FONSECA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 4,
        inscricao: 252400021,
        nome: "MARIA DA CONCEIÇÃO VIEIRA DE SOUZA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 5,
        inscricao: 252400023,
        nome: "SARAH DE OLIVEIRA VIEIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 6,
        inscricao: 252400031,
        nome: "ROSANGELA PRICILA DE OLIVEIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 7,
        inscricao: 252400036,
        nome: "DAIANE FRANCINE GONÇALVES FREITAS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 8,
        inscricao: 252400039,
        nome: "FABIA RIBEIRO LIMA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 9,
        inscricao: 252400042,
        nome: "ZENÁLIA BARBOS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 10,
        inscricao: 252400045,
        nome: "MÁRCIA APARECIDA CARDOSO DE OLIVEIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 11,
        inscricao: 252400047,
        nome: "LUCELIA SANTOS PEREIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 12,
        inscricao: 252400048,
        nome: "SOLANGE MARIA VILAÇA DE FARIA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 13,
        inscricao: 252400049,
        nome: "ADRIANA CRISTIELLE FERREIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 14,
        inscricao: 252400051,
        nome: "MARIA FERNANDA PEREIRA DE JESUS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 15,
        inscricao: 252400052,
        nome: "CARLA NAYARA DE JESUS SANTOS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },
    {
        id: 16,
        inscricao: 252400007,
        nome: "IAGO LEAL DE FREITAS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 17,
        inscricao: 252400009,
        nome: "NEIDE DA ROCHA DO NASCIMENTO",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 18,
        inscricao: 252400015,
        nome: "LUCIMARLY TAVARES DA FONSECA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 19,
        inscricao: 252400021,
        nome: "MARIA DA CONCEIÇÃO VIEIRA DE SOUZA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 20,
        inscricao: 252400023,
        nome: "SARAH DE OLIVEIRA VIEIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 21,
        inscricao: 252400031,
        nome: "ROSANGELA PRICILA DE OLIVEIRA",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },

    {
        id: 22,
        inscricao: 252400036,
        nome: "DAIANE FRANCINE GONÇALVES FREITAS",
        perfil: "Banca da Prova",
        n_inscricoes: 250,
        n_cotas: 125,
        n_recursos: 72,
        n_matriculas: 128,
    },


];
export default data;